import os, glob, re, json

# 1. Collect all valid routes generated by Next.js
# We can get all valid routes from:
# - pages_registry.json
# - service_pages.json
# - trainings.json (slug -> /pelatihan/[slug])
# - articles.json (slug -> /artikel/[slug])
# - glossary.json (slug -> /glosarium/[slug])
# - incidents.json (slug -> /insiden/[slug])
# - core static pages

valid_routes = set([
    '/',
    '/pelatihan',
    '/jadwal',
    '/perusahaan',
    '/csms',
    '/galeri',
    '/artikel',
    '/tools',
    '/tools/safety-talk',
    '/tools/jsa-builder',
    '/tools/ibpr-generator',
    '/tools/apd-selector',
    '/tools/ai-analyzer',
    '/tools/kalkulator-k3',
    '/tools/kalkulator-kebisingan',
    '/tools/kalkulator-biaya-k3',
    '/tools/laporan-insiden',
    '/tools/regulasi-k3',
    '/tools/risk-matrix',
    '/tools/social-generator',
    '/glosarium',
    '/insiden',
    '/verifikasi',
    '/kebijakan-privasi',
    '/forum',
    '/lowongan',
    '/resources',
    '/sitemap.xml',
    '/robots.txt'
])

# Load dynamic datasets
if os.path.exists('src/data/service_pages.json'):
    with open('src/data/service_pages.json', 'r', encoding='utf-8') as f:
        sp = json.load(f)
        for k in sp.keys():
            valid_routes.add(f"/{k}")

if os.path.exists('src/data/pages_registry.json'):
    with open('src/data/pages_registry.json', 'r', encoding='utf-8') as f:
        pr = json.load(f)
        for k in pr.keys():
            valid_routes.add(f"/{k}")

if os.path.exists('src/data/trainings.json'):
    with open('src/data/trainings.json', 'r', encoding='utf-8') as f:
        tr = json.load(f)
        for t in tr:
            valid_routes.add(f"/pelatihan/{t['slug']}")

if os.path.exists('src/data/articles.json'):
    with open('src/data/articles.json', 'r', encoding='utf-8') as f:
        ar = json.load(f)
        for a in ar:
            valid_routes.add(f"/artikel/{a['slug']}")

if os.path.exists('src/data/glossary.json'):
    with open('src/data/glossary.json', 'r', encoding='utf-8') as f:
        gl = json.load(f)
        for g in gl:
            valid_routes.add(f"/glosarium/{g['slug']}")

if os.path.exists('src/data/incidents.json'):
    with open('src/data/incidents.json', 'r', encoding='utf-8') as f:
        inc = json.load(f)
        for i in inc:
            valid_routes.add(f"/insiden/{i['slug']}")

print(f"Total valid known routes in Next.js: {len(valid_routes)}")

# 2. Extract every internal URL from all source code in src/
source_files = glob.glob('src/**/*', recursive=True)
all_links = []

for sf in source_files:
    if os.path.isdir(sf):
        continue
    if not (sf.endswith('.tsx') or sf.endswith('.ts') or sf.endswith('.json')):
        continue
    
    with open(sf, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    
    # Match href="..." or href={`...`} or url: "..."
    hrefs = re.findall(r'href=["\'](/[^"\']*)["\']', content)
    hrefs += re.findall(r'href=\{`(/[^`]*)`\}', content)
    hrefs += re.findall(r'"url":\s*["\'](/[^"\']*)["\']', content)
    
    for h in hrefs:
        # clean query params or hashes
        clean_h = h.split('?')[0].split('#')[0].rstrip('/')
        if not clean_h:
            clean_h = '/'
        all_links.append({
            'source_file': sf,
            'raw_href': h,
            'clean_route': clean_h
        })

print(f"Total extracted internal link references: {len(all_links)}")

# 3. Check for broken / 404 internal links
broken_links = []
for item in all_links:
    route = item['clean_route']
    # If route contains template placeholders like ${...} or params, skip
    if '$' in route or '{' in route or '[' in route:
        continue
    
    if route not in valid_routes:
        broken_links.append(item)

print(f"\nTotal broken / 404 links found: {len(broken_links)}")
for b in broken_links[:30]:
    print(f"  [BROKEN] {b['clean_route']:45s} in {b['source_file']}")
