import os, glob, re, json

# 1. Collect all valid routes generated by Next.js
valid_routes = set([
    '/',
    '/pelatihan',
    '/jadwal',
    '/perusahaan',
    '/perpanjangan-skp',
    '/csms',
    '/galeri',
    '/artikel',
    '/tools',
    '/tools/safety-talk',
    '/tools/jsa-builder',
    '/tools/ibpr-generator',
    '/tools/apd-selector',
    '/tools/ai-analyzer',
    '/tools/kalkulator-k3',
    '/tools/kalkulator-kebisingan',
    '/tools/kalkulator-biaya-k3',
    '/tools/laporan-insiden',
    '/tools/regulasi-k3',
    '/tools/risk-matrix',
    '/tools/social-generator',
    '/glosarium',
    '/insiden',
    '/verifikasi',
    '/kebijakan-privasi',
    '/forum',
    '/lowongan',
    '/resources',
    '/sitemap.xml',
    '/robots.txt'
])

# Load modular datasets
if os.path.exists('src/data/services/services.json'):
    with open('src/data/services/services.json', 'r', encoding='utf-8') as f:
        sp = json.load(f)
        for k in sp.keys():
            valid_routes.add(f"/{k}")

if os.path.exists('src/data/pages_registry.json'):
    with open('src/data/pages_registry.json', 'r', encoding='utf-8') as f:
        pr = json.load(f)
        for k in pr.keys():
            valid_routes.add(f"/{k}")

if os.path.exists('src/data/trainings/all.json'):
    with open('src/data/trainings/all.json', 'r', encoding='utf-8') as f:
        tr = json.load(f)
        for item in tr:
            valid_routes.add(f"/pelatihan/{item['slug']}")

if os.path.exists('src/data/cities/city_pelatihan_cleaned.json'):
    with open('src/data/cities/city_pelatihan_cleaned.json', 'r', encoding='utf-8') as f:
        cp = json.load(f)
        for k in cp.keys():
            valid_routes.add(f"/pelatihan/{k}")

if os.path.exists('src/data/articles/all.json'):
    with open('src/data/articles/all.json', 'r', encoding='utf-8') as f:
        ar = json.load(f)
        for item in ar:
            valid_routes.add(f"/artikel/{item['slug']}")

if os.path.exists('src/data/glossary.json'):
    with open('src/data/glossary.json', 'r', encoding='utf-8') as f:
        gl = json.load(f)
        for item in gl:
            valid_routes.add(f"/glosarium/{item['slug']}")

if os.path.exists('src/data/incidents.json'):
    with open('src/data/incidents.json', 'r', encoding='utf-8') as f:
        inc = json.load(f)
        for item in inc:
            valid_routes.add(f"/insiden/{item['slug']}")

print(f"Total valid target routes recognized: {len(valid_routes)}")

# 2. Scan all TSX and JSON data files for internal links
broken_links = []
checked_links = 0

def check_link(source_file, link):
    global checked_links
    if not link or link.startswith('#') or link.startswith('tel:') or link.startswith('mailto:') or link.startswith('https://wa.me') or link.startswith('http://') or link.startswith('https://'):
        return
    
    clean_link = link.split('?')[0].split('#')[0]
    if clean_link.endswith('/') and len(clean_link) > 1:
        clean_link = clean_link[:-1]
    
    if not clean_link:
        clean_link = '/'

    checked_links += 1
    if clean_link not in valid_routes and f"{clean_link}" not in valid_routes:
        broken_links.append((source_file, link, clean_link))

# Scan all TSX files
for filepath in glob.glob('src/**/*.tsx', recursive=True):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    hrefs = re.findall(r'href=["\']([^"\']+)["\']', content)
    for h in hrefs:
        check_link(filepath, h)

print(f"Scanned {checked_links} internal links across codebase.")
if broken_links:
    print(f"[!] Found {len(broken_links)} potential broken links:")
    for src, raw, clean in broken_links[:10]:
        print(f"  - In {src}: {raw} -> {clean}")
else:
    print("[SUCCESS] All internal links are 100% valid! Zero broken links found.")
