import os, glob, re, json

# 1. Collect all valid routes generated by Next.js
valid_routes = set([
    '/',
    '/pelatihan',
    '/jadwal',
    '/perusahaan',
    '/csms',
    '/galeri',
    '/artikel',
    '/tools',
    '/tools/safety-talk',
    '/tools/jsa-builder',
    '/tools/ibpr-generator',
    '/tools/apd-selector',
    '/tools/ai-analyzer',
    '/tools/kalkulator-k3',
    '/tools/kalkulator-kebisingan',
    '/tools/kalkulator-biaya-k3',
    '/tools/laporan-insiden',
    '/tools/regulasi-k3',
    '/tools/risk-matrix',
    '/tools/social-generator',
    '/glosarium',
    '/insiden',
    '/verifikasi',
    '/kebijakan-privasi',
    '/forum',
    '/lowongan',
    '/resources',
    '/sitemap.xml',
    '/robots.txt'
])

def load_json(path):
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

sp = load_json('src/data/service_pages.json')
for k in sp.keys():
    valid_routes.add(f"/{k}")

pr = load_json('src/data/pages_registry.json')
for k in pr.keys():
    valid_routes.add(f"/{k}")

tr = load_json('src/data/trainings.json')
for t in tr:
    valid_routes.add(f"/pelatihan/{t['slug']}")

ar = load_json('src/data/articles.json')
for a in ar:
    valid_routes.add(f"/artikel/{a['slug']}")

gl = load_json('src/data/glossary.json')
for g in gl:
    valid_routes.add(f"/glosarium/{g['slug']}")

inc = load_json('src/data/incidents.json')
for i in inc:
    valid_routes.add(f"/insiden/{i['slug']}")

print(f"Total valid target routes: {len(valid_routes)}")

# 2. Check all JSON datasets for internal HTML links
datasets = ['src/data/service_pages.json', 'src/data/articles.json', 'src/data/trainings.json', 'src/data/glossary.json', 'src/data/safety_talks.json']

broken_in_json = []

for ds_path in datasets:
    if not os.path.exists(ds_path):
        continue
    with open(ds_path, 'r', encoding='utf-8') as f:
        raw_text = f.read()
    
    # Extract href="/..."
    hrefs = re.findall(r'href=["\'](/[^"\']*)["\']', raw_text)
    for h in set(hrefs):
        clean_h = h.split('?')[0].split('#')[0].rstrip('/')
        if not clean_h:
            clean_h = '/'
        if clean_h.startswith('/images') or clean_h.startswith('/assets') or clean_h.startswith('/favicon'):
            continue
        if clean_h not in valid_routes:
            broken_in_json.append({'file': ds_path, 'href': h, 'clean': clean_h})

print(f"Broken links found in JSON datasets: {len(broken_in_json)}")
for b in broken_in_json[:20]:
    print(f"  [BROKEN IN JSON] {b['clean']:45s} in {b['file']}")
